name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker containers
        run: |
          docker-compose up -d --build

      - name: Run database backup
        run: |
          chmod +x scripts/backup_database.sh
          ./scripts/backup_database.sh

      - name: Send email notification
        run: |
          chmod +x scripts/send_email.sh
          ./scripts/send_email.sh

      - name: Stop and remove Docker containers
        run: |
          docker-compose down
