

services:
  app:
    build: /app
    container_name: node-js.app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
       - DATABASE_URL=mysql://user:password@mysql:3306/mydb

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  mysql_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter
    environment:
      - DATA_SOURCE_NAME=user:password@(mysql:3306)/mydb
    depends_on:
      - mysql
    ports:
      - "9104:9104"


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_lab
    #depends_on:
      #- mysql_exporter
    volumes:
      - ./prometheus.yml:/etc/prometheus/app/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_new
    # depends_on:
      #- prometheus
    ports:
      - "3000:3000"

volumes:
  mysqldata:
