name: docker-compose and backup script pipeline

on:
  workflow_dispatch:

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Install Docker compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      
      - name: Run Docker Compose  
        run: docker-compose up -d

      - name: Check docker containers
        run: docker-compose ps

      - name: Wait for MySQL to be Ready
        run: |
          for i in {1..10}; do
            if docker exec mysql mysqladmin ping -u root -prootpassword --silent; then
              echo "MySQL is ready."
              break
            fi
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done
          


      - name: make script executable
        run: chmod +x ./backup_mysql.sh

      - name: Run backup script
        run: ./backup_mysql.sh
        



      

  # run-backup-script:
  #   runs-on: ubuntu-latest
  #   needs: run-docker-compose
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
     
  #     - name: Make backup script executable
  #       run: chmod +x ./backup_mysql.sh
             
  #     - name: Run backup script
  #       run: ./backup_mysql.sh
  #       #run: bash ./backup.sh
