name: docker-compose and backup script pipeline

on:
  workflow_dispatch:

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      
      - name: Run Docker Compose
        working-directory: .
        run: docker-compose up -d

  run-backup-script:
    runs-on: ubuntu-latest
    needs: run-docker-compose
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Run backup script
        run: ./backup_mysql.sh
        #run: bash ./backup.sh